Histories
misasa/sisyphus pull request #6
Opened 2016-12-06 09:47 UTC by ke-matsumoto

Implement history window.

- added a button of history to Main tab
- assed a window of history(extend a window of search)

- [ ] code review

2016-12-07 09:35 UTC, m-imaoka requested changes

2016-12-07 09:35 UTC, m-imaoka commented on Resources/sisyphus/ui/android/AddChildWindow.js
> +                                    );
履歴の最大保持件数によっては、ここの処理は重くなりそうですね。
特にストレスを感じない応答速度なら良いですが、若干引っかかりを覚えるようであれば、
保持対象となる最小の日時を取得して、それ以下のレコードは削除するというような処理にした方が良いと思います。

以下にコードイメージを示します。
```
loaded_at_min = SELECT MIN(loaded_at) FROM histories ORDER BY loaded_at DESC LIMIT HISTORY_MAX_COUNT;
DELETE FROM histories WHERE loaded_at < loaded_at_min
```

2016-12-07 10:13 UTC, akikosakamoto01 commented on Resources/sisyphus/ui/SearchWindow.js
>          //TODO: layout
ただの消し忘れでしかないので、このTODOコメント消していただいてもよいデス・・・

2016-12-07 10:45 UTC, akikosakamoto01 commented
そのたLGTMです！

2016-12-08 04:18 UTC, ke-matsumoto commented on Resources/sisyphus/ui/android/AddChildWindow.js
> +                                    );
→`MAX_COUNT`以上のレコードの日時を取得し、それ以下のレコードを削除する処理へ修正しました。
`Fixed max count deletion processing.`https://github.com/misasa/sisyphus/pull/6/commits/ca2c1d0020ec816e2bfdb1f5e7f4e99195436a36

2016-12-22 00:08 UTC, m-imaoka approved these changes
LGTM

2016-12-22 06:37 UTC, merged